language: ruby
rvm:
- 2.2.0
script:
- bundle exec rake db:migrate --trace
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec -fd spec/
deploy:
  provider: heroku
  api_key:
    secure: XxHHu5oJfhzHwrc8448+VbVPHw81RTckrMlU/DA/MuMBjpuNHKBYOtYjtImmFgbr+NDi2+m2DP2bM3CZNYsqrtIrIxqK76mMK5AK+VIQ71u/Z/Uk/bCDPyKeVyNom6JcbhzovGI58TRKjLOL8tjcSdoReoDsQo8zxD28P9AduE4=
  app: ror-scheduler
  on:
    repo: wakr/scheduler
  addons:
    code_climate:
      repo_token: fcb12968ec0b28f892d130a83ae38c82a9ac3988019281697c7def4e0cfbee19
